# [START gke_manifests_helloweb_hpa_horizontalpodautoscaler_cpu]
# [START container_helloapp_horizontal_pod_autoscaler]
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloweb
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
# [END container_helloapp_horizontal_pod_autoscaler]
# [END gke_manifests_helloweb_hpa_horizontalpodautoscaler_cpu]
---
